import Vue from 'vue';
import Vuetify,{
    VApp,
    VAppBar,
    VNavigationDrawer,
    VToolbar,
    VContainer,
    VContent,
    VRow,
    VCol,
    VList,
    VListItem,
    VListItemContent,
    VListItemTitle,
    VListItemAction,
    VIcon,
    VAppBarNavIcon,
    VToolbarTitle,
    VTooltip,
    VFooter,
    VBtn,
    VCard,
    VCardTitle,
    VCardSubtitle,
    VCardText,
    VCardActions,
    VImg,
    VDivider,
    VRating,
    VSpacer,
    VForm,
    VTextField,
    VSelect,
    VCheckbox,
    VTextarea,
    VFileInput,
} from 'vuetify/lib';

Vue.use(Vuetify,{
    components: {
        VApp,
        VAppBar,
        VNavigationDrawer,
        VToolbar,
        VContainer,
        VContent,
        VRow,
        VCol,
        VList,
        VListItem,
        VListItemContent,
        VListItemTitle,
        VListItemAction,
        VIcon,
        VAppBarNavIcon,
        VToolbarTitle,
        VTooltip,
        VFooter,
        VBtn,
        VCard,
        VCardTitle,
        VCardSubtitle,
        VCardText,
        VCardActions,
        VImg,
        VDivider,
        VRating,
        VSpacer,
        VForm,
        VTextField,
        VSelect,
        VCheckbox,
        VTextarea,
        VFileInput,
    }
});

const opts = {};
export default new Vuetify(opts);